name: WETH8
plugins:
  # So we can compile METH
  - name: huff
  # So we can compile WETH9 and WETH10
  - name: solidity
  # So we can compile our project
  - name: vyper

dependencies:
  - name: weth9
    github: tongyuhu/weth9
    ref: master
  - name: weth10
    github: WETH10/WETH10
    ref: main
  - name: meth_weth
    github: Philogy/meth-weth
    ref: main
    contracts_folder: src

solidity:
  version: 0.8.20

huff:
  version: 0.3.2

test:
  gas:
    exclude:
      - contract_name: TestFlashReceiver
