on: ["push", "pull_request"]

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@refactor/github-output-file
    - run: ape compile --size
    - run: ape test -s
