on: ["push", "pull_request"]

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ApeWorX/github-action@v2
      with:
        python-version: '3.10'
    - run: ape compile --size
    - run: ape test -s
